config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'restaurants#index'
  get 'reviews/new'
  resources :restaurants, only: [ :index, :show, :new, :create ] do
    resources :reviews, only: [ :new, :create ]
  end
  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"]
  has_many :reviews, dependent: :destroy
  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: CATEGORIES }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, :rating, presence: true
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[show]

  def index
    @restaurants = Restaurant.all
  end

  def show; end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: %i[new create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    # raise
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant), status: :see_other
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<div class='container'>
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category %>
  </div>
  <div class="form-actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>
</div>

app/views/restaurants/_list.html.erb
<div id="restaurants" class='card pt-3'>
  <% restaurants.each do |restaurant| %>
    <%= render restaurant %>
      <%= link_to "Show this restaurant", restaurant, class: 'btn btn-primary m-3 text-white text-decoration-none'%>
  <% end %>
</div>

app/views/restaurants/_restaurant.html.erb
<div id="<%= dom_id restaurant %>">
  <div class='card p-3'>
    <p class='m-0'>
      <strong>Name:</strong>
      <%= restaurant.name %>
    </p>

    <p class='m-0'>
      <strong>Address:</strong>
      <%= restaurant.address %>
    </p>

    <p class='m-0'>
      <strong>Phone number:</strong>
      <%= restaurant.phone_number %>
    </p>

    <p class='m-0'>
      <strong>Category:</strong>
      <%= restaurant.category %>
    </p>
  </div>
</div>

app/views/restaurants/index.html.erb
<div class="container">
  <h1>Restaurant list:</h1>
  <hr/>
  <%= render "restaurants/list", restaurants: @restaurants %>
  <%= link_to 'Add new restaurant', new_restaurant_path, class: "btn btn-primary my-3 text-white text-decoration-none" %>
</div>

app/views/restaurants/new.html.erb
<div class='container'>
<h1>Create the new Restaurant</h1>
<%= render 'form' %>
</div>

app/views/restaurants/show.html.erb
<div class='container'>
<p style="color: green"><%= notice %></p>

<%= render @restaurant %>

<p><strong>Reviews:</strong></p>
<ul class="list-group">
  <% @restaurant.reviews.each do |review| %>
    <li class="list-group-item">
      Review: <%= review.content %> | Rating: <%= review.rating %>
    </li>
  <% end %>
</ul>

<div>
  <%= link_to "Add review to this restaurant", restaurant_path + reviews_new_path %>
  |
  <%= link_to "Back to restaurants", restaurants_path %>
</div>

</div>

app/views/reviews/new.html.erb
<div class='container'>
<h1>New Review</h1>
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>
</div>